// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilcltmoupymaxgymeqgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsY2x0bW91cHltYXhneW1lcWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTY0NTYsImV4cCI6MjA2Njg3MjQ1Nn0.FrJjj6CGP86N55PjIa9mL9GvVpsFvEYNxs6x5tDvLJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});